name: park
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.2
  - torchvision=0.17
  - torchaudio=2.2
  - pytorch-cuda=12.1
  - numpy=1.24
  - pandas=2.1
  - scikit-learn=1.4
  - seaborn=0.12
  - ipykernel
  - pip
  - pip:
      - wandb==0.16.2
      - baal==1.9.1
      - imbalanced-learn==0.12
      - plotly==5.21.0
      - kaleido==0.2.1
      - torchmetrics==0.9.3
      - timm==1.0.9
      - pytorch-lightning==1.9.5
      - mlxtend==0.23.1
      - nbformat>=4.2
      - great_tables==0.13.0
      - selenium==4.25.0
      - matplotlib-venn==0.11.10
      - shap==0.46.0
      - opencv-python-headless==4.10.0.84
      - mediapipe==0.10.11
      - smogn==0.1.2
      - soundfile==0.12.1
      - transformers==4.41.2
      - openai-whisper
